-- V5__add_user_and_ownership.sql

-- 1. Create the users table to store local user information linked to the OIDC provider.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    provider_user_id VARCHAR(255) NOT NULL UNIQUE
);

-- 2. Add the 'created_by_user_id' column to the existing 'application' table
--    to track which user created which application.
ALTER TABLE application
ADD COLUMN created_by_user_id BIGINT;

-- 3. Add the foreign key constraint to link the new column to the 'users' table.
ALTER TABLE application
ADD CONSTRAINT fk_application_created_by
FOREIGN KEY (created_by_user_id) REFERENCES users(id);
